openapi: 3.0.0
info:
  title: Sports API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/arafathnihar/Petstore/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /product:
    get:
      responses:
        200:
          description: This is a list of the products
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      format: int32
                      example: 123
                    name:
                      type: string
                      example: football
components: {}
