openapi: 3.0.0
info:
  title: Sports store API
  version: 1.0.0
servers:
- url: /
paths:
  /product:
    get:
      responses:
        200:
          description: This is a list of the products
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      format: int32
                      example: 1
                    name:
                      type: string
                      example: football
components: {}
